### ISSUE TITLE
unused for Q table

### ISSUE THREAD

**Issue by lynnhuang97** [fengcong1992/QLearningForecast#1]
Hello,  fengcong, @fengcong1992,
I'm quite interested in your work for Q-learning in Dynamic model selection, thanks a lot for your open source.
Now I'm trying to understand the paper and code, and find a question there:

It seems that the Q table is not used in Qlearning_DMS.R.
The raw code: 

>   for (j in 1:no_hour) {
>     state_step <- vector_best[j]
>     result_dayp <- c(result_dayp, df_select[(j+1), state_step])
>     result_dayp_selection <- c(result_dayp_selection, colnames(df_select)[which.max(Q_table[state_step,])+1])
>   }
> 
>   return_obj <- result_dayp

It probably should be:

>   for (j in 1:no_hour) {
>     state_step <- vector_best[j]
>     # result_dayp <- c(result_dayp, df_select[(j+1), state_step])
>     result_dayp <- c(result_dayp, df_select[(j+1), colnames(df_select)[which.max(Q_table[state_step,])+1]])
>     result_dayp_selection <- c(result_dayp_selection, colnames(df_select)[which.max(Q_table[state_step,])+1])
>   }
> 
>   return_obj <- result_dayp
>   return(return_obj)
> }

Otherwise the Q table is unused. I tried to set Q_table <- diag(QMS_no_models), the lower result outputs the same as the upper, which means the system just use the best model of t-1.

Also, the data in code is different with that in paper, as the latter covers 365days in 2015, however the former only covers 5days. How could I find the data and code for the experiment in paper?

**Comment by fengcong1992** [comment]
Thanks for pointing this out. The wrong version of the code (testing the Qlearning-selected model with the best model every step) was uploaded.
